name: Non-master Branch

on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'

jobs:

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.16
      - name: Maven Verify
        run: mvn -B clean verify -DskipITs
  component-test:
    name: Component Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.16
      - name: Maven Verify
        run: mvn -B clean verify -DskipITs