name: Non-master-or-release Branch
# only run unit tests on push to any non-master or non-release branch. 
# Component tests will be run on PRs to master
on:
  push:
    branches-ignore:
      - master
      - main
      - release*

jobs:

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11.0.16
      - name: Maven Verify - skip IT (i.e., component) tests
        run: mvn -B clean verify -DskipITs