name: Pull Request to Master

on:
# pushes and pulls into master/main will be handled on a separate workflow
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master

jobs:

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11.0.16
      - name: Maven Verify
        run: mvn -B clean verify -DskipITs
  component-test:
    name: Component Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11.0.16
      - name: Maven Verify
        run: mvn -B clean verify -DskipITs
  